// 2025 NFL Fantasy Draft Results Data

export interface DraftPick {
  pick: number;
  player: string;
  position: string;
  team: string;
  salary: number;
  owner: string;
  nflTeam: string;
}

export const TEAM_MAPPING: Record<string, string> = {
  'CLAM MAN': 'Kevin',
  'Quadzilla': 'Nicky', 
  'ComeOn': 'Colby',
  'Beerbongs & Barkleys': 'Sean',
  'The Chili Beans': 'John',
  'City Footbaw': 'Zack',
  'Not so back': 'Pat',
  'Bearer of the Cha...': 'Binit',
  'Lookin\' Purdy Week 8': 'Anonymous',
  'Brock\'s Trusty Fr...': 'Grossy',
  'Schizo Spreadsheets': 'Bryan',
  'CeeDeez Nuts': 'Joey'
};

// Parse player info from draft string
function parsePlayerInfo(playerStr: string): { player: string; position: string; nflTeam: string } {
  const match = playerStr.match(/^(.+?)\s+\((\w+)\s+-\s+(\w+)\)$/);
  if (match) {
    return {
      player: match[1].trim(),
      position: match[3],
      nflTeam: match[2].toUpperCase()
    };
  }
  return { player: playerStr, position: 'UNKNOWN', nflTeam: 'UNKNOWN' };
}

export const COMPLETE_DRAFT_DATA: DraftPick[] = [
  { pick: 180, ...parsePlayerInfo('Marvin Mims Jr. (Den - WR)'), salary: 1, team: 'Den', owner: 'Zack' },
  { pick: 179, ...parsePlayerInfo('Minnesota (Min - DEF)'), salary: 1, team: 'Min', owner: 'Zack' },
  { pick: 178, ...parsePlayerInfo('Jerome Ford (Cle - RB)'), salary: 1, team: 'Cle', owner: 'Zack' },
  { pick: 177, ...parsePlayerInfo('Jonnu Smith (Pit - TE)'), salary: 1, team: 'Pit', owner: 'Zack' },
  { pick: 176, ...parsePlayerInfo('Bryce Young (Car - QB)'), salary: 1, team: 'Car', owner: 'Zack' },
  { pick: 175, ...parsePlayerInfo('Tyjae Spears (Ten - RB)'), salary: 1, team: 'Ten', owner: 'Zack' },
  { pick: 174, ...parsePlayerInfo('Isaac Guerendo (SF - RB)'), salary: 1, team: 'SF', owner: 'John' },
  { pick: 173, ...parsePlayerInfo('Aaron Rodgers (Pit - QB)'), salary: 1, team: 'Pit', owner: 'Kevin' },
  { pick: 172, ...parsePlayerInfo('Luther Burden III (Chi - WR)'), salary: 1, team: 'Chi', owner: 'Anonymous' },
  { pick: 171, ...parsePlayerInfo('Chris Godwin (TB - WR)'), salary: 5, team: 'TB', owner: 'Binit' },
  { pick: 170, ...parsePlayerInfo('Tyler Allgeier (Atl - RB)'), salary: 1, team: 'Atl', owner: 'John' },
  { pick: 169, ...parsePlayerInfo('Detroit (Det - DEF)'), salary: 1, team: 'Det', owner: 'Sean' },
  { pick: 168, ...parsePlayerInfo('Houston (Hou - DEF)'), salary: 1, team: 'Hou', owner: 'Kevin' },
  { pick: 167, ...parsePlayerInfo('Chase McLaughlin (TB - K)'), salary: 1, team: 'TB', owner: 'Anonymous' },
  { pick: 166, ...parsePlayerInfo('Jordan Love (GB - QB)'), salary: 1, team: 'GB', owner: 'Binit' },
  { pick: 165, ...parsePlayerInfo('Travis Etienne Jr. (Jax - RB)'), salary: 2, team: 'Jax', owner: 'Binit' },
  { pick: 164, ...parsePlayerInfo('Woody Marks (Hou - RB)'), salary: 1, team: 'Hou', owner: 'John' },
  { pick: 163, ...parsePlayerInfo('Evan McPherson (Cin - K)'), salary: 1, team: 'Cin', owner: 'Sean' },
  { pick: 162, ...parsePlayerInfo('Mitchell Tinsley (Cin - WR)'), salary: 1, team: 'Cin', owner: 'Colby' },
  { pick: 161, ...parsePlayerInfo('Harrison Butker (KC - K)'), salary: 1, team: 'KC', owner: 'Kevin' },
  { pick: 160, ...parsePlayerInfo('Ka\'imi Fairbairn (Hou - K)'), salary: 6, team: 'Hou', owner: 'Joey' },
  { pick: 159, ...parsePlayerInfo('Brenton Strange (Jax - TE)'), salary: 3, team: 'Jax', owner: 'Anonymous' },
  { pick: 158, ...parsePlayerInfo('Washington (Was - DEF)'), salary: 1, team: 'Was', owner: 'Binit' },
  { pick: 157, ...parsePlayerInfo('Darnell Mooney (Atl - WR)'), salary: 1, team: 'Atl', owner: 'Zack' },
  { pick: 156, ...parsePlayerInfo('Jaydon Blue (Dal - RB)'), salary: 2, team: 'Dal', owner: 'Zack' },
  { pick: 155, ...parsePlayerInfo('Jake Bates (Det - K)'), salary: 2, team: 'Det', owner: 'Binit' },
  { pick: 154, ...parsePlayerInfo('Jake Elliott (Phi - K)'), salary: 1, team: 'Phi', owner: 'Colby' },
  { pick: 153, ...parsePlayerInfo('Christian Kirk (Hou - WR)'), salary: 1, team: 'Hou', owner: 'Kevin' },
  { pick: 152, ...parsePlayerInfo('Kansas City (KC - DEF)'), salary: 1, team: 'KC', owner: 'Joey' },
  { pick: 151, ...parsePlayerInfo('Jake Ferguson (Dal - TE)'), salary: 6, team: 'Dal', owner: 'John' },
  { pick: 150, ...parsePlayerInfo('Jaylen Wright (Mia - RB)'), salary: 2, team: 'Mia', owner: 'Binit' },
  { pick: 149, ...parsePlayerInfo('Colston Loveland (Chi - TE)'), salary: 7, team: 'Chi', owner: 'Anonymous' },
  { pick: 148, ...parsePlayerInfo('Dylan Sampson (Cle - RB)'), salary: 3, team: 'Cle', owner: 'John' },
  { pick: 147, ...parsePlayerInfo('Javonte Williams (Dal - RB)'), salary: 4, team: 'Dal', owner: 'Sean' },
  { pick: 146, ...parsePlayerInfo('Rashod Bateman (Bal - WR)'), salary: 1, team: 'Bal', owner: 'Colby' },
  { pick: 145, ...parsePlayerInfo('Austin Ekeler (Was - RB)'), salary: 15, team: 'Was', owner: 'Nicky' },
  { pick: 144, ...parsePlayerInfo('Philadelphia (Phi - DEF)'), salary: 2, team: 'Phi', owner: 'Kevin' },
  { pick: 143, ...parsePlayerInfo('Trevor Lawrence (Jax - QB)'), salary: 3, team: 'Jax', owner: 'Joey' },
  { pick: 142, ...parsePlayerInfo('Cam Skattebo (NYG - RB)'), salary: 14, team: 'NYG', owner: 'Grossy' },
  { pick: 141, ...parsePlayerInfo('Kyle Pitts Sr. (Atl - TE)'), salary: 8, team: 'Atl', owner: 'Nicky' },
  { pick: 140, ...parsePlayerInfo('J.J. McCarthy (Min - QB)'), salary: 3, team: 'Min', owner: 'Colby' },
  { pick: 139, ...parsePlayerInfo('Pittsburgh (Pit - DEF)'), salary: 1, team: 'Pit', owner: 'Pat' },
  { pick: 138, ...parsePlayerInfo('Josh Downs (Ind - WR)'), salary: 4, team: 'Ind', owner: 'Sean' },
  { pick: 137, ...parsePlayerInfo('Caleb Williams (Chi - QB)'), salary: 1, team: 'Chi', owner: 'John' },
  { pick: 136, ...parsePlayerInfo('Jayden Reed (GB - WR)'), salary: 2, team: 'GB', owner: 'Sean' },
  { pick: 135, ...parsePlayerInfo('Nick Chubb (Hou - RB)'), salary: 1, team: 'Hou', owner: 'Colby' },
  { pick: 134, ...parsePlayerInfo('Keon Coleman (Buf - WR)'), salary: 1, team: 'Buf', owner: 'Nicky' },
  { pick: 133, ...parsePlayerInfo('Dallas Goedert (Phi - TE)'), salary: 3, team: 'Phi', owner: 'Kevin' },
  { pick: 132, ...parsePlayerInfo('Rashid Shaheed (NO - WR)'), salary: 6, team: 'NO', owner: 'Joey' },
  { pick: 131, ...parsePlayerInfo('Cameron Dicker (LAC - K)'), salary: 4, team: 'LAC', owner: 'Bryan' },
  { pick: 130, ...parsePlayerInfo('Trey Benson (Ari - RB)'), salary: 9, team: 'Ari', owner: 'Grossy' },
  { pick: 129, ...parsePlayerInfo('Arizona (Ari - DEF)'), salary: 1, team: 'Ari', owner: 'Anonymous' },
  { pick: 128, ...parsePlayerInfo('Rhamondre Stevenson (NE - RB)'), salary: 5, team: 'NE', owner: 'Binit' },
  { pick: 127, ...parsePlayerInfo('New England (NE - DEF)'), salary: 3, team: 'NE', owner: 'Nicky' },
  { pick: 126, ...parsePlayerInfo('Bhayshul Tuten (Jax - RB)'), salary: 4, team: 'Jax', owner: 'Bryan' },
  { pick: 125, ...parsePlayerInfo('Kyler Murray (Ari - QB)'), salary: 2, team: 'Ari', owner: 'John' },
  { pick: 124, ...parsePlayerInfo('Khalil Shakir (Buf - WR)'), salary: 5, team: 'Buf', owner: 'Anonymous' },
  { pick: 123, ...parsePlayerInfo('Buffalo (Buf - DEF)'), salary: 3, team: 'Buf', owner: 'Colby' },
  { pick: 122, ...parsePlayerInfo('Joe Mixon (Hou - RB)'), salary: 1, team: 'Hou', owner: 'Nicky' },
  { pick: 121, ...parsePlayerInfo('Evan Engram (Den - TE)'), salary: 7, team: 'Den', owner: 'Bryan' },
  { pick: 120, ...parsePlayerInfo('Michael Pittman Jr. (Ind - WR)'), salary: 5, team: 'Ind', owner: 'Joey' },
  { pick: 119, ...parsePlayerInfo('Tank Bigsby (Jax - RB)'), salary: 7, team: 'Jax', owner: 'Pat' },
  { pick: 118, ...parsePlayerInfo('Denver (Den - DEF)'), salary: 3, team: 'Den', owner: 'Grossy' },
  { pick: 117, ...parsePlayerInfo('Matthew Golden (GB - WR)'), salary: 3, team: 'GB', owner: 'Anonymous' },
  { pick: 116, ...parsePlayerInfo('Rachaad White (TB - RB)'), salary: 3, team: 'TB', owner: 'Colby' },
  { pick: 115, ...parsePlayerInfo('Tucker Kraft (GB - TE)'), salary: 6, team: 'GB', owner: 'Pat' },
  { pick: 114, ...parsePlayerInfo('Emeka Egbuka (TB - WR)'), salary: 15, team: 'TB', owner: 'Grossy' },
  { pick: 113, ...parsePlayerInfo('Justin Fields (NYJ - QB)'), salary: 3, team: 'NYJ', owner: 'Binit' },
  { pick: 112, ...parsePlayerInfo('Will Shipley (Phi - RB)'), salary: 1, team: 'Phi', owner: 'Sean' },
  { pick: 111, ...parsePlayerInfo('Jauan Jennings (SF - WR)'), salary: 5, team: 'SF', owner: 'Binit' },
  { pick: 110, ...parsePlayerInfo('C.J. Stroud (Hou - QB)'), salary: 4, team: 'Hou', owner: 'Nicky' },
  { pick: 109, ...parsePlayerInfo('Zach Charbonnet (Sea - RB)'), salary: 4, team: 'Sea', owner: 'Anonymous' },
  { pick: 108, ...parsePlayerInfo('Mark Andrews (Bal - TE)'), salary: 7, team: 'Bal', owner: 'Joey' },
  { pick: 107, ...parsePlayerInfo('Drake Maye (NE - QB)'), salary: 4, team: 'NE', owner: 'Bryan' },
  { pick: 106, ...parsePlayerInfo('Braelon Allen (NYJ - RB)'), salary: 7, team: 'NYJ', owner: 'Bryan' },
  { pick: 105, ...parsePlayerInfo('Cooper Kupp (Sea - WR)'), salary: 8, team: 'Sea', owner: 'Pat' },
  { pick: 104, ...parsePlayerInfo('Justin Herbert (LAC - QB)'), salary: 4, team: 'LAC', owner: 'John' },
  { pick: 103, ...parsePlayerInfo('Stefon Diggs (NE - WR)'), salary: 11, team: 'NE', owner: 'Joey' },
  { pick: 102, ...parsePlayerInfo('J.K. Dobbins (Den - RB)'), salary: 3, team: 'Den', owner: 'Grossy' },
  { pick: 101, ...parsePlayerInfo('Jared Goff (Det - QB)'), salary: 2, team: 'Det', owner: 'Anonymous' },
  { pick: 100, ...parsePlayerInfo('Brandon Aubrey (Dal - K)'), salary: 3, team: 'Dal', owner: 'Nicky' },
  { pick: 99, ...parsePlayerInfo('Rome Odunze (Chi - WR)'), salary: 11, team: 'Chi', owner: 'John' },
  { pick: 98, ...parsePlayerInfo('Jordan Mason (Min - RB)'), salary: 5, team: 'Min', owner: 'Grossy' },
  { pick: 97, ...parsePlayerInfo('Deebo Samuel (Was - WR)'), salary: 9, team: 'Was', owner: 'Kevin' },
  { pick: 96, ...parsePlayerInfo('Tyrone Tracy Jr. (NYG - RB)'), salary: 6, team: 'NYG', owner: 'Joey' },
  { pick: 95, ...parsePlayerInfo('Jaylen Warren (Pit - RB)'), salary: 6, team: 'Pit', owner: 'Bryan' },
  { pick: 94, ...parsePlayerInfo('Quinshon Judkins (Cle - RB)'), salary: 11, team: 'Cle', owner: 'Bryan' },
  { pick: 93, ...parsePlayerInfo('Tyler Warren (Ind - TE)'), salary: 9, team: 'Ind', owner: 'Nicky' },
  { pick: 92, ...parsePlayerInfo('Chris Olave (NO - WR)'), salary: 10, team: 'NO', owner: 'Bryan' },
  { pick: 91, ...parsePlayerInfo('Jakobi Meyers (LV - WR)'), salary: 10, team: 'LV', owner: 'Nicky' },
  { pick: 90, ...parsePlayerInfo('Zay Flowers (Bal - WR)'), salary: 17, team: 'Bal', owner: 'Nicky' },
  { pick: 89, ...parsePlayerInfo('Tetairoa McMillan (Car - WR)'), salary: 8, team: 'Car', owner: 'Grossy' },
  { pick: 88, ...parsePlayerInfo('Ricky Pearsall (SF - WR)'), salary: 4, team: 'SF', owner: 'Pat' },
  { pick: 87, ...parsePlayerInfo('Brock Purdy (SF - QB)'), salary: 7, team: 'SF', owner: 'Anonymous' },
  { pick: 86, ...parsePlayerInfo('Jameson Williams (Det - WR)'), salary: 12, team: 'Det', owner: 'Nicky' },
  { pick: 85, ...parsePlayerInfo('Jerry Jeudy (Cle - WR)'), salary: 8, team: 'Cle', owner: 'Nicky' },
  { pick: 84, ...parsePlayerInfo('Patrick Mahomes (KC - QB)'), salary: 9, team: 'KC', owner: 'Joey' },
  { pick: 83, ...parsePlayerInfo('Tony Pollard (Ten - RB)'), salary: 16, team: 'Ten', owner: 'John' },
  { pick: 82, ...parsePlayerInfo('Cam Little (Jax - K)'), salary: 1, team: 'Jax', owner: 'Grossy' },
  { pick: 81, ...parsePlayerInfo('Davante Adams (LAR - WR)'), salary: 20, team: 'LAR', owner: 'Bryan' },
  { pick: 80, ...parsePlayerInfo('Raheem Mostert (LV - RB)'), salary: 1, team: 'LV', owner: 'Binit' },
  { pick: 79, ...parsePlayerInfo('Baltimore (Bal - DEF)'), salary: 4, team: 'Bal', owner: 'Bryan' },
  { pick: 78, ...parsePlayerInfo('Dak Prescott (Dal - QB)'), salary: 7, team: 'Dal', owner: 'Zack' },
  { pick: 77, ...parsePlayerInfo('Kaleb Johnson (Pit - RB)'), salary: 16, team: 'Pit', owner: 'Bryan' },
  { pick: 76, ...parsePlayerInfo('Roschon Johnson (Chi - RB)'), salary: 1, team: 'Chi', owner: 'Sean' },
  { pick: 75, ...parsePlayerInfo('Baker Mayfield (TB - QB)'), salary: 6, team: 'TB', owner: 'Pat' },
  { pick: 74, ...parsePlayerInfo('Aaron Jones Sr. (Min - RB)'), salary: 8, team: 'Min', owner: 'Pat' },
  { pick: 73, ...parsePlayerInfo('Hunter Henry (NE - TE)'), salary: 1, team: 'NE', owner: 'Kevin' },
  { pick: 72, ...parsePlayerInfo('T.J. Hockenson (Min - TE)'), salary: 8, team: 'Min', owner: 'Joey' },
  { pick: 71, ...parsePlayerInfo('Isiah Pacheco (KC - RB)'), salary: 11, team: 'KC', owner: 'John' },
  { pick: 70, ...parsePlayerInfo('Jaylen Waddle (Mia - WR)'), salary: 8, team: 'Mia', owner: 'Joey' },
  { pick: 69, ...parsePlayerInfo('Travis Hunter (Jax - WR)'), salary: 8, team: 'Jax', owner: 'Anonymous' },
  { pick: 68, ...parsePlayerInfo('Jordan Addison (Min - WR)'), salary: 4, team: 'Min', owner: 'Grossy' },
  { pick: 67, ...parsePlayerInfo('George Pickens (Dal - WR)'), salary: 11, team: 'Dal', owner: 'Pat' },
  { pick: 66, ...parsePlayerInfo('D\'Andre Swift (Chi - RB)'), salary: 9, team: 'Chi', owner: 'Zack' },
  { pick: 65, ...parsePlayerInfo('DJ Moore (Chi - WR)'), salary: 11, team: 'Chi', owner: 'Kevin' },
  { pick: 64, ...parsePlayerInfo('Keenan Allen (LAC - WR)'), salary: 4, team: 'LAC', owner: 'Grossy' },
  { pick: 63, ...parsePlayerInfo('Sam LaPorta (Det - TE)'), salary: 11, team: 'Det', owner: 'Colby' },
  { pick: 62, ...parsePlayerInfo('Travis Kelce (KC - TE)'), salary: 6, team: 'KC', owner: 'Grossy' },
  { pick: 61, ...parsePlayerInfo('DK Metcalf (Pit - WR)'), salary: 17, team: 'Pit', owner: 'Kevin' },
  { pick: 60, ...parsePlayerInfo('David Montgomery (Det - RB)'), salary: 8, team: 'Det', owner: 'Joey' },
  { pick: 59, ...parsePlayerInfo('Brian Robinson Jr. (Was - RB)'), salary: 7, team: 'Was', owner: 'Sean' },
  { pick: 58, ...parsePlayerInfo('Joe Burrow (Cin - QB)'), salary: 17, team: 'Cin', owner: 'Kevin' },
  { pick: 57, ...parsePlayerInfo('Garrett Wilson (NYJ - WR)'), salary: 22, team: 'NYJ', owner: 'Joey' },
  { pick: 56, ...parsePlayerInfo('Joshua Palmer (Buf - WR)'), salary: 2, team: 'Buf', owner: 'Binit' },
  { pick: 55, ...parsePlayerInfo('RJ Harvey (Den - RB)'), salary: 17, team: 'Den', owner: 'Pat' },
  { pick: 54, ...parsePlayerInfo('Jalen Hurts (Phi - QB)'), salary: 16, team: 'Phi', owner: 'Grossy' },
  { pick: 53, ...parsePlayerInfo('A.J. Brown (Phi - WR)'), salary: 33, team: 'Phi', owner: 'Grossy' },
  { pick: 52, ...parsePlayerInfo('Courtland Sutton (Den - WR)'), salary: 18, team: 'Den', owner: 'Sean' },
  { pick: 51, ...parsePlayerInfo('Calvin Ridley (Ten - WR)'), salary: 7, team: 'Ten', owner: 'Sean' },
  { pick: 50, ...parsePlayerInfo('Alvin Kamara (NO - RB)'), salary: 27, team: 'NO', owner: 'John' },
  { pick: 49, ...parsePlayerInfo('Terry McLaurin (Was - WR)'), salary: 20, team: 'Was', owner: 'Kevin' },
  { pick: 48, ...parsePlayerInfo('Chuba Hubbard (Car - RB)'), salary: 21, team: 'Car', owner: 'Pat' },
  { pick: 47, ...parsePlayerInfo('Jacory Croskey-Merritt (Was - RB)'), salary: 1, team: 'Was', owner: 'Bryan' },
  { pick: 46, ...parsePlayerInfo('James Conner (Ari - RB)'), salary: 15, team: 'Ari', owner: 'Kevin' },
  { pick: 45, ...parsePlayerInfo('Marvin Harrison Jr. (Ari - WR)'), salary: 21, team: 'Ari', owner: 'Nicky' },
  { pick: 44, ...parsePlayerInfo('George Kittle (SF - TE)'), salary: 23, team: 'SF', owner: 'Colby' },
  { pick: 43, ...parsePlayerInfo('Tyreek Hill (Mia - WR)'), salary: 23, team: 'Mia', owner: 'Colby' },
  { pick: 42, ...parsePlayerInfo('David Njoku (Cle - TE)'), salary: 3, team: 'Cle', owner: 'Zack' },
  { pick: 41, ...parsePlayerInfo('De\'Von Achane (Mia - RB)'), salary: 43, team: 'Mia', owner: 'Binit' },
  { pick: 40, ...parsePlayerInfo('Bo Nix (Den - QB)'), salary: 6, team: 'Den', owner: 'Sean' },
  { pick: 39, ...parsePlayerInfo('Xavier Worthy (KC - WR)'), salary: 14, team: 'KC', owner: 'Pat' },
  { pick: 38, ...parsePlayerInfo('Rashee Rice (KC - WR)'), salary: 10, team: 'KC', owner: 'John' },
  { pick: 37, ...parsePlayerInfo('Mike Evans (TB - WR)'), salary: 29, team: 'TB', owner: 'Colby' },
  { pick: 36, ...parsePlayerInfo('Tee Higgins (Cin - WR)'), salary: 29, team: 'Cin', owner: 'Joey' },
  { pick: 35, ...parsePlayerInfo('Breece Hall (NYJ - RB)'), salary: 18, team: 'NYJ', owner: 'Anonymous' },
  { pick: 34, ...parsePlayerInfo('Kenneth Walker III (Sea - RB)'), salary: 21, team: 'Sea', owner: 'Sean' },
  { pick: 33, ...parsePlayerInfo('Kyren Williams (LAR - RB)'), salary: 31, team: 'LAR', owner: 'Anonymous' },
  { pick: 32, ...parsePlayerInfo('Chase Brown (Cin - RB)'), salary: 39, team: 'Cin', owner: 'Zack' },
  { pick: 31, ...parsePlayerInfo('Bucky Irving (TB - RB)'), salary: 39, team: 'TB', owner: 'Binit' },
  { pick: 30, ...parsePlayerInfo('Jonathan Taylor (Ind - RB)'), salary: 38, team: 'Ind', owner: 'Nicky' },
  { pick: 29, ...parsePlayerInfo('Omarion Hampton (LAC - RB)'), salary: 28, team: 'LAC', owner: 'Grossy' },
  { pick: 28, ...parsePlayerInfo('Dalton Kincaid (Buf - TE)'), salary: 1, team: 'Buf', owner: 'Sean' },
  { pick: 27, ...parsePlayerInfo('James Cook (Buf - RB)'), salary: 25, team: 'Buf', owner: 'Colby' },
  { pick: 26, ...parsePlayerInfo('Puka Nacua (LAR - WR)'), salary: 48, team: 'LAR', owner: 'Anonymous' },
  { pick: 25, ...parsePlayerInfo('Jayden Daniels (Was - QB)'), salary: 28, team: 'Was', owner: 'Bryan' },
  { pick: 24, ...parsePlayerInfo('Brian Thomas Jr. (Jax - WR)'), salary: 44, team: 'Jax', owner: 'John' },
  { pick: 23, ...parsePlayerInfo('Drake London (Atl - WR)'), salary: 42, team: 'Atl', owner: 'Bryan' },
  { pick: 22, ...parsePlayerInfo('TreVeyon Henderson (NE - RB)'), salary: 17, team: 'NE', owner: 'Pat' },
  { pick: 21, ...parsePlayerInfo('Trey McBride (Ari - TE)'), salary: 27, team: 'Ari', owner: 'Binit' },
  { pick: 20, ...parsePlayerInfo('Jaxon Smith-Njigba (Sea - WR)'), salary: 25, team: 'Sea', owner: 'Zack' },
  { pick: 19, ...parsePlayerInfo('Ladd McConkey (LAC - WR)'), salary: 32, team: 'LAC', owner: 'Bryan' },
  { pick: 18, ...parsePlayerInfo('Amon-Ra St. Brown (Det - WR)'), salary: 54, team: 'Det', owner: 'Zack' },
  { pick: 17, ...parsePlayerInfo('CeeDee Lamb (Dal - WR)'), salary: 62, team: 'Dal', owner: 'John' },
  { pick: 16, ...parsePlayerInfo('Lamar Jackson (Bal - QB)'), salary: 35, team: 'Bal', owner: 'Pat' },
  { pick: 15, ...parsePlayerInfo('Josh Jacobs (GB - RB)'), salary: 37, team: 'GB', owner: 'Colby' },
  { pick: 14, ...parsePlayerInfo('Justin Jefferson (Min - WR)'), salary: 62, team: 'Min', owner: 'Binit' },
  { pick: 13, ...parsePlayerInfo('Josh Allen (Buf - QB)'), salary: 36, team: 'Buf', owner: 'Colby' },
  { pick: 12, ...parsePlayerInfo('Bijan Robinson (Atl - RB)'), salary: 71, team: 'Atl', owner: 'Joey' },
  { pick: 11, ...parsePlayerInfo('Derrick Henry (Bal - RB)'), salary: 48, team: 'Bal', owner: 'Kevin' },
  { pick: 10, ...parsePlayerInfo('Christian McCaffrey (SF - RB)'), salary: 53, team: 'SF', owner: 'Kevin' },
  { pick: 9, ...parsePlayerInfo('Jahmyr Gibbs (Det - RB)'), salary: 59, team: 'Det', owner: 'Anonymous' },
  { pick: 8, ...parsePlayerInfo('Ashton Jeanty (LV - RB)'), salary: 50, team: 'LV', owner: 'Nicky' },
  { pick: 7, ...parsePlayerInfo('DeVonta Smith (Phi - WR)'), salary: 13, team: 'Phi', owner: 'Pat' },
  { pick: 6, ...parsePlayerInfo('Malik Nabers (NYG - WR)'), salary: 51, team: 'NYG', owner: 'Grossy' },
  { pick: 5, ...parsePlayerInfo('Nico Collins (Hou - WR)'), salary: 54, team: 'Hou', owner: 'Zack' },
  { pick: 4, ...parsePlayerInfo('Kimani Vidal (LAC - RB)'), salary: 2, team: 'LAC', owner: 'Colby' },
  { pick: 3, ...parsePlayerInfo('Ja\'Marr Chase (Cin - WR)'), salary: 66, team: 'Cin', owner: 'Sean' },
  { pick: 2, ...parsePlayerInfo('Brock Bowers (LV - TE)'), salary: 32, team: 'LV', owner: 'Pat' },
  { pick: 1, ...parsePlayerInfo('Saquon Barkley (Phi - RB)'), salary: 60, team: 'Phi', owner: 'Sean' }
].map(pick => ({
  ...pick,
  nflTeam: pick.nflTeam || pick.team.toUpperCase()
}));

// Yahoo average auction values (2025 updated estimates based on consensus)
export const YAHOO_ADP_DATA: Record<string, number> = {
  'Saquon Barkley': 67,
  'Brock Bowers': 32,
  'Ja\'Marr Chase': 59,
  'Kimani Vidal': 3,
  'Nico Collins': 52,
  'Malik Nabers': 51,
  'DeVonta Smith': 13,
  'Ashton Jeanty': 53,
  'Jahmyr Gibbs': 65,
  'Christian McCaffrey': 54,
  'Derrick Henry': 52,
  'Bijan Robinson': 66,
  'Josh Allen': 36,
  'Justin Jefferson': 55,
  'Josh Jacobs': 37,
  'Lamar Jackson': 35,
  'CeeDee Lamb': 53,
  'Amon-Ra St. Brown': 54,
  'Ladd McConkey': 32,
  'Jaxon Smith-Njigba': 25,
  'Trey McBride': 27,
  'TreVeyon Henderson': 17,
  'Drake London': 42,
  'Brian Thomas Jr.': 44,
  'Jayden Daniels': 28,
  'Puka Nacua': 52,
  'James Cook': 25,
  'Dalton Kincaid': 1,
  'Omarion Hampton': 28,
  'Jonathan Taylor': 38,
  'Bucky Irving': 39,
  'Chase Brown': 39,
  'Kyren Williams': 31,
  'Kenneth Walker III': 21,
  'Breece Hall': 18,
  'Tee Higgins': 29,
  'Mike Evans': 29,
  'Rashee Rice': 10,
  'Xavier Worthy': 14,
  'Bo Nix': 6,
  'De\'Von Achane': 43,
  'David Njoku': 3,
  'Tyreek Hill': 23,
  'George Kittle': 23,
  'Marvin Harrison Jr.': 21,
  'James Conner': 15,
  'Jacory Croskey-Merritt': 1,
  'Chuba Hubbard': 21,
  'Terry McLaurin': 20,
  'Alvin Kamara': 27,
  'Jalen Hurts': 16,
  'A.J. Brown': 33,
  'Courtland Sutton': 18,
  'Calvin Ridley': 7,
  'RJ Harvey': 17,
  'Joshua Palmer': 2,
  'Garrett Wilson': 22,
  'Joe Burrow': 17,
  'Brian Robinson Jr.': 7,
  'David Montgomery': 8,
  'DK Metcalf': 17,
  'Travis Kelce': 6,
  'Sam LaPorta': 11,
  'Keenan Allen': 4,
  'DJ Moore': 11,
  'D\'Andre Swift': 9,
  'George Pickens': 11,
  'Jordan Addison': 4,
  'Travis Hunter': 8,
  'Jaylen Waddle': 8,
  'Isiah Pacheco': 11,
  'T.J. Hockenson': 8,
  'Hunter Henry': 1,
  'Aaron Jones Sr.': 8,
  'Baker Mayfield': 6,
  'Roschon Johnson': 1,
  'Kaleb Johnson': 16,
  'Dak Prescott': 7,
  'Baltimore': 4,
  'Raheem Mostert': 1,
  'Davante Adams': 20,
  'Cam Little': 1,
  'Tony Pollard': 16,
  'Patrick Mahomes': 9,
  'Jerry Jeudy': 8,
  'Jameson Williams': 12,
  'Brock Purdy': 7,
  'Ricky Pearsall': 4,
  'Tetairoa McMillan': 8,
  'Zay Flowers': 17,
  'Jakobi Meyers': 10,
  'Chris Olave': 10,
  'Tyler Warren': 9,
  'Quinshon Judkins': 11,
  'Jaylen Warren': 6,
  'Tyrone Tracy Jr.': 6,
  'Deebo Samuel': 9,
  'Jordan Mason': 5,
  'Rome Odunze': 11,
  'Brandon Aubrey': 3,
  'Jared Goff': 2,
  'J.K. Dobbins': 3,
  'Stefon Diggs': 11,
  'Justin Herbert': 4,
  'Cooper Kupp': 8,
  'Braelon Allen': 7,
  'Drake Maye': 4,
  'Mark Andrews': 7,
  'Zach Charbonnet': 4,
  'C.J. Stroud': 4,
  'Jauan Jennings': 5,
  'Will Shipley': 1,
  'Justin Fields': 3,
  'Emeka Egbuka': 15,
  'Tucker Kraft': 6,
  'Rachaad White': 3,
  'Matthew Golden': 3,
  'Denver': 3,
  'Tank Bigsby': 7,
  'Michael Pittman Jr.': 5,
  'Evan Engram': 7,
  'Joe Mixon': 1,
  'Buffalo': 3,
  'Khalil Shakir': 5,
  'Kyler Murray': 2,
  'Bhayshul Tuten': 4,
  'New England': 3,
  'Rhamondre Stevenson': 5,
  'Arizona': 1,
  'Trey Benson': 9,
  'Cameron Dicker': 4,
  'Rashid Shaheed': 6,
  'Dallas Goedert': 3,
  'Keon Coleman': 1,
  'Nick Chubb': 1,
  'Jayden Reed': 2,
  'Caleb Williams': 1,
  'Josh Downs': 4,
  'Pittsburgh': 1,
  'J.J. McCarthy': 3,
  'Kyle Pitts Sr.': 8,
  'Cam Skattebo': 14,
  'Trevor Lawrence': 3,
  'Philadelphia': 2,
  'Austin Ekeler': 15,
  'Rashod Bateman': 1,
  'Javonte Williams': 4,
  'Dylan Sampson': 3,
  'Colston Loveland': 7,
  'Jaylen Wright': 2,
  'Jake Ferguson': 6,
  'Kansas City': 1,
  'Christian Kirk': 1,
  'Jake Elliott': 1,
  'Jake Bates': 2,
  'Jaydon Blue': 2,
  'Darnell Mooney': 1,
  'Washington': 1,
  'Brenton Strange': 3,
  'Ka\'imi Fairbairn': 6,
  'Harrison Butker': 1,
  'Mitchell Tinsley': 1,
  'Evan McPherson': 1,
  'Woody Marks': 1,
  'Travis Etienne Jr.': 2,
  'Jordan Love': 1,
  'Chase McLaughlin': 1,
  'Houston': 1,
  'Detroit': 1,
  'Tyler Allgeier': 1,
  'Chris Godwin': 5,
  'Luther Burden III': 1,
  'Aaron Rodgers': 1,
  'Isaac Guerendo': 1,
  'Tyjae Spears': 1,
  'Bryce Young': 1,
  'Jonnu Smith': 1,
  'Jerome Ford': 1,
  'Minnesota': 1,
  'Marvin Mims Jr.': 1
};

export const POSITION_TIERS = {
  QB: {
    'Tier 1': ['Josh Allen', 'Lamar Jackson', 'Jayden Daniels'],
    'Tier 2': ['Patrick Mahomes', 'Joe Burrow', 'Jalen Hurts'],
    'Tier 3': ['C.J. Stroud', 'Brock Purdy', 'Dak Prescott', 'Bo Nix'],
    'Tier 4': ['Baker Mayfield', 'Justin Herbert', 'Drake Maye'],
    'Tier 5': ['Trevor Lawrence', 'Justin Fields', 'Caleb Williams', 'J.J. McCarthy', 'Kyler Murray']
  },
  RB: {
    'Tier 1': ['Christian McCaffrey', 'Saquon Barkley', 'Bijan Robinson'],
    'Tier 2': ['Jahmyr Gibbs', 'Derrick Henry', 'Ashton Jeanty'],
    'Tier 3': ['Jonathan Taylor', 'Bucky Irving', 'Chase Brown', 'De\'Von Achane'],
    'Tier 4': ['Josh Jacobs', 'Kyren Williams', 'Alvin Kamara', 'James Cook'],
    'Tier 5': ['Omarion Hampton', 'Kenneth Walker III', 'Chuba Hubbard', 'Breece Hall', 'TreVeyon Henderson']
  },
  WR: {
    'Tier 1': ['Ja\'Marr Chase', 'Justin Jefferson', 'CeeDee Lamb'],
    'Tier 2': ['Nico Collins', 'Amon-Ra St. Brown', 'Malik Nabers'],
    'Tier 3': ['Puka Nacua', 'Brian Thomas Jr.', 'Drake London'],
    'Tier 4': ['Ladd McConkey', 'Tee Higgins', 'Mike Evans'],
    'Tier 5': ['Jaxon Smith-Njigba', 'Marvin Harrison Jr.', 'DeVonta Smith', 'Terry McLaurin']
  },
  TE: {
    'Tier 1': ['Brock Bowers', 'Trey McBride'],
    'Tier 2': ['George Kittle', 'Sam LaPorta'],
    'Tier 3': ['Mark Andrews', 'T.J. Hockenson', 'Travis Kelce'],
    'Tier 4': ['Tyler Warren', 'Kyle Pitts Sr.', 'Evan Engram'],
    'Tier 5': ['Dallas Goedert', 'David Njoku', 'Tucker Kraft']
  }
};

export function getPlayerTier(player: string, position: string): string {
  const tiers = POSITION_TIERS[position as keyof typeof POSITION_TIERS];
  if (!tiers) return 'Unknown';
  
  for (const [tier, players] of Object.entries(tiers)) {
    if (players.includes(player)) {
      return tier;
    }
  }
  return 'Deep';
}